language: cpp

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./HelloCMake

after_success:
  - lcov --capture --directory . --output-file coverage/coverage.info --no-external
